### ISSUE TITLE
Questions about Benchmark Test Datasets

### ISSUE THREAD

**Issue by Gaoxj2020** [wangyuxin87/VisionLAN#13]
How many images do you use in Benchmark Datasets IIIT5K, SVT, IC13, IC15, SVTP, and CUTE80 respectively? I am confused with the 4832 images you mentioned in your paper.
Thank you!

**Comment by wangyuxin87** [comment]
We just randomly choose 4832 images in these benchmarks. We have provided these test datasets. To be specific,  IIIT5K:3000, SVT:647, IC13:857, IC15:1811, SVTP:645, and CUTE80:288.

**Comment by Gaoxj2020** [comment]
> We just randomly choose 4832 images in these benchmarks. We have provided these test datasets. To be specific, IIIT5K:3000, SVT:647, IC13:857, IC15:1811, SVTP:645, and CUTE80:288.

It's my problem that I didn't read the article carefully. 
Your work has inspired me a lot. Thank you for your contribution！
