### ISSUE TITLE
关于VRM的一个问题

### ISSUE THREAD

**Issue by tambourine666** [wangyuxin87/VisionLAN#3]
您好，感谢您的工作，启发很大，关于文章中的VRM有个小问题。请问VRM的结构是什么样的？是只有多层transformer encoder的叠加，还是transformer后还做了parallel attention?

期待您的回复！

**Comment by wangyuxin87** [comment]
感谢关注，VRM将transformer encoder后的视觉特征输入预测层，预测层里面有parallel attention
