### ISSUE TITLE
Is that a typo?

### ISSUE THREAD

**Issue by JingyeChen** [wangyuxin87/VisionLAN#5]
Hello! It is an excellent work that inspires me a lot ;D
As I read your code, I found something strange (maybe a typo):

# train_LA.py
line145: text_pre, test_rem, text_mas, att_mask_sub = model(data, label_id, cfgs.global_cfgs['step'])

Should "test_rem" be modified to "text_rem"?

**Comment by wangyuxin87** [comment]
Thanks for pointing out this problem, it has been fixed.

**Comment by JingyeChen** [comment]
Thank you!
